; NodeMCU V3 (ESP8266MOD) Sensor Dashboard - PlatformIO Configuration

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Libraries
lib_deps = 
    ESP32Async/ESPAsyncWebServer @ ^3.7.6
    ESP32Async/ESPAsyncTCP @ ^2.0.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/Arduino_JSON @ ^0.2.0

; Build-Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=0
